variables:
  IAM_ROLE_PARAM: /dagster/s3-sample/RoleArn
  BUCKET_NAME_PARAM: /dagster/s3-sample/BucketName
  DS_TARGET_IMAGE_NAME: dagster-s3-sample
  CODE_LOCATION_VERSION: 0.0.3
  DOCKER_SRC_DIR: src/Docker

code-location-deployment:
  stage: .post
  variables:
    JOB_CF_ENVIRONMENT: DEV
    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID_DEV
  image: $CDK_IMAGE:$DOCKER_TAG
  tags:
    - auto
  before_script:
    - !reference [ .scripts, proxy ]
    - !reference [.scripts, aws, setup]
    - !reference [.scripts, aws, credentials]
  script:
    - pwd
    - ls -a
    - echo "############################"
    - echo "### Setting Environment Parameter"
    - echo "############################"
    - IAM_ROLE_ARN=$(aws ssm get-parameter --name $IAM_ROLE_PARAM --query "Parameter.Value" --output text)
    - export IAM_ROLE_ARN=$IAM_ROLE_ARN
    - S3_BUCKET=$(aws ssm get-parameter --name $BUCKET_NAME_PARAM --query "Parameter.Value" --output text)
    - export S3_BUCKET=$S3_BUCKET
    - echo "############################"
    - echo "### Starting Docker build   "
    - echo "############################"
    - echo $HARBOR_USER_PWD | docker login --username $HARBOR_USER --password-stdin $HARBOR_URL/
    - docker build -t $HARBOR_SHORT_URL/$HARBOR_PROJECT/$DS_TARGET_IMAGE_NAME:$CODE_LOCATION_VERSION -f $DOCKER_SRC_DIR/Dockerfile . --build-arg s3_bucket_name=$S3_BUCKET --build-arg iam_role_arn=$IAM_ROLE_ARN --build-arg http_proxy=$PROXY --build-arg https_proxy=$PROXY
    - docker push $HARBOR_SHORT_URL/$HARBOR_PROJECT/$DS_TARGET_IMAGE_NAME:$CODE_LOCATION_VERSION
    - echo "############################"
    - echo "### Finished Docker build   "
    - echo "############################"
#    - pip install dagster-cloud
#    - dagster-cloud --install-completion
#    - dagster-cloud config set-deployment prod --organization hdi --api-token agent:hdi:4b47eb7501974f5980345d7d03a38643
#    - dagster-cloud workspace add-location s3_sample --image $HARBOR_SHORT_URL/$HARBOR_PROJECT/$DS_TARGET_IMAGE_NAME:$CODE_LOCATION_VERSION --package-name s3_sample