version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
# So far there is no need for specific loggers
#loggers:
#  __main__:
#    level: INFO
#    handlers: [console]
#    propagate: no
root:
  level: INFO
  handlers: [console]
